development:
  adapter: mysql
  database: jobs_dev
  username: root
  password: password
  host: localhost
  socket: /var/lib/mysql/mysql.sock

test: &TEST
  adapter: mysql
  database: jobs_test
  username: root
  password: password
  host: localhost
  socket: /var/lib/mysql/mysql.sock

staging:
  adapter: mysql
  database: tj_staging
  username: tj
  password: password
  host: localhost
  socket: /var/lib/mysql/mysql.sock
  
production:
  adapter: mysql
  database: jobs
  username: jobs
  password: password
  host: localhost
  socket: /var/lib/mysql/mysql.sock
  
cucumber:
  <<: *TEST